#!/bin/bash
echo '--------- LOGGING : UBUNTU-USB BACKUP ---------' `date`;
sudo rsync -tav --delete --exclude-from=/home/ubuntu/Desktop/usb-backup.exclude.middle /media/ubuntu/f1d67fbc-39b4-4565-a632-4495d83372f7/ /media/ubuntu/22b37cfd-603e-4eda-b058-1ba6d281c80b;
