#!/bin/bash
echo '--------- LOGGING : UBUNTU-USB BACKUP ---------' `date`;
sudo rsync -tav --delete --exclude-from=/home/ubuntu/Desktop/usb-backup.exclude.middle /media/ubuntu/5047007c-3dc3-4880-97e9-d8836e8f0539/ /media/ubuntu/22b37cfd-603e-4eda-b058-1ba6d281c80b;
