#!/bin/bash
echo '--------- LOGGING : UBUNTU-USB BACKUP ---------' `date`;
sudo rsync -tav --delete --exclude-from=/home/zhuylanz/script/usb-backup.exclude / /media/zhuylanz/5047007c-3dc3-4880-97e9-d8836e8f0539;
