#!/bin/bash
echo '--------- LOGGING : UBUNTU-USB BACKUP ---------' `date`;
sudo rsync -tav --delete --exclude-from=/home/zhuylanz/script/usb-backup.exclude / /media/zhuylanz/22b37cfd-603e-4eda-b058-1ba6d281c80b;
