#!/bin/bash
wpa_supplicant -i wlp3s0 -c /etc/wpa_supplicant/wpa_supplicant.conf -B dhclient
ifconfig wlp3s0 192.168.1.151 netmask 255.255.255.0 up
route add default gw 192.168.1.1
echo 'nameserver 8.8.8.8' >> /etc/resolv.conf
echo 'nameserver 8.8.4.4' >> /etc/resolv.conf
