#!/bin/bash
ifconfig eth0 192.168.151.3 netmask 255.255.255.0
ip route add 192.168.151.0/24 dev eth0
ip route add default via 192.168.151.1
echo 'nameserver 8.8.8.8' >> /etc/resolv.conf
echo 'nameserver 8.8.4.4' >> /etc/resolv.conf
