#!/bin/bash
sudo apt-get install -y fcitx-unikey curl clipit gnome-tweak-tool gnome-shell-extensions
#nodejs
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
#sublime text 3
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt-get update
sudo apt-get install -y sublime-text
#google chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
sudo apt-get update 
sudo apt-get install -y google-chrome-stable
#adapta theme
sudo add-apt-repository ppa:tista/adapta
sudo apt-get update
sudo apt-get install -y adapta-gtk-theme
#pop76 theme
sudo add-apt-repository ppa:system76/pop
sudo apt-get update
sudo apt-get install -y pop-icon-theme
